### ISSUE TITLE
Dovecot Configuration

### ISSUE THREAD

**Issue by Mischback** [Mischback/mailsrv#14]
## Relevant ``Dovecot`` settings

- [x] ``10-auth.conf``
  - [x] ``auth_mechanism``: ``Outlook`` requires ``login``, ``plain`` is the default
  - [x] review the different authentication backends with ``Dovecot``'s documentation
- [x] ``10-mail.conf``
  - [x] ``mail_location``
    - guide suggests ``maildir:~/Maildir``, but as we are (mainly) concerned about virtual users, how does this work?
  - [x] ``mail_plugins``: add ``quota`` to manage the size of users' mailboxes
- [x] ``10-master.conf``
  - [x] provide the authentication socket required by ``Postfix``:
    ```
    # Postfix smtp-auth
    unix_listener /var/spool/postfix/private/auth {
      mode = 0660
      user = postfix
      group = postfix
    }
    ```
  - [x] create the ``lmtp`` socket for ``Postfix`` (might already be there, configure accordingly)
    ```
    service lmtp {
      unix_listener /var/spool/postfix/private/dovecot-lmtp {
        group = postfix
        mode = 0600
        user = postfix
      }
    }
    ```
  - [x] review other settings here!
- [x] ``10-ssl.conf``
  - [x] ``ssl_cert`` and ``ssl_key``: Point to the respective files
    - [x] **IMPORTANT** syntax is like ``ssl_cert = </etc/letsencrypt/live/webmail.example.org/fullchain.pem``, making the content of the certificate available!
- ~~``20-lmtp.conf``~~
  - ~~if *server side* ``sieve`` should be applied, activate the plugin here (needs packet installation)~~
  - tracked in #21 
- [x] ``90-quota.conf``
  - [x] Provide the actual mailbox quota
    ```
    plugin {
      quota = maildir:User quota

      quota_status_success = DUNNO
      quota_status_nouser = DUNNO
      quota_status_overquota = "452 4.2.2 Mailbox is full and cannot receive any more emails"
    }
    ```
  - [x] provide the endpoint (socket) for ``Postfix``
    ```
    service quota-status {
      executable = /usr/lib/dovecot/quota-status -p postfix
      unix_listener /var/spool/postfix/private/quota-status {
        user = postfix
      }
    }
    ```
    - [x] Why is the definition of ``unix_listener`` lacking ``mode`` and ``group`` settings, as they are present in the other socket definitions?
  - [x] the actual ``quota`` must be provided by the ``user_db``; needs investigation!
  - [x] Enable warnings about quotas:
    ```
    plugin {
       quota_warning = storage=95%% quota-warning 95 %u
       quota_warning2 = storage=80%% quota-warning 80 %u
    }
    service quota-warning {
       executable = script /usr/local/bin/quota-warning.sh  # Adjust script path!
       unix_listener quota-warning {
         user = vmail
         group = vmail
         mode = 0660
       }
    }
    ```
  - [x] The referenced script to send the users emails about their quotas:
    ```
    #!/bin/sh
    PERCENT=$1
    USER=$2
    cat << EOF | /usr/lib/dovecot/dovecot-lda -d $USER -o "plugin/quota=maildir:User quota:noenforcing"
    From: postmaster@webmail.example.org
    Subject: Quota warning - $PERCENT% reached

    Your mailbox can only store a limited amount of emails.
    Currently it is $PERCENT% full. If you reach 100% then
    new emails cannot be stored. Thanks for your understanding.
    EOF
    ```
- [x] **Important** somewhere is the ``user_db`` setting. This needs careful attention, because my setup will not rely on SQL as backend (deviating from the tutorial!); see https://doc.dovecot.org/configuration_manual/authentication/user_databases_userdb/ and https://doc.dovecot.org/configuration_manual/authentication/passwd_file/#authentication-passwd-file

**Comment by Mischback** [comment]
Basic implementation completed as of f749eb01c201f1f5d85f6997177c45bd0d1cd80b

- Dovecot is up and running
- Dovecot is providing user-management for Postfix
- Dovecot is providing IMAP / POP3 (with default settings)
- Dovecot is working as Postfix's LDA
